name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - name: Install dependencies
        run: composer install
      - name: pint check
        run: composer check-style
  phpunit:
    strategy:
      matrix:
        php_version: [8.0, 8.1, 8.2, 8.3, 8.4]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: xdebug
      - name: Install dependencies
        run: composer install
      - name: PHPUnit check
        run: ./vendor/bin/phpunit --coverage-text
